[gcloud]
disabled = true

[directory]
read_only = "ó°Œ¾ "

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) coding in '

[docker_context]
symbol = "ïŒˆ "
disabled = true

[elixir]
symbol = "î‰µ "

[git_branch]
symbol = "ï˜ "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[golang]
symbol = "î˜§ "

[python]
disabled = true

# [java]
# symbol = "î‰– "

[memory_usage]
symbol = " "
threshold = 75
disabled = true

[nodejs]
symbol = "îœ˜ "
disabled = true

# [package]
# symbol = "î¬© "

[rust]
symbol = "î¨ "

[ruby]
symbol = "ğŸ’ "

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
# disabled = true

[[battery.display]]
threshold = 80

# [shell]
# unknown_indicator = 'mystery shell'
# style = 'red bold'
# disabled = false
