[gcloud]
disabled = true

[directory]
read_only = "ï ½ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[git_branch]
symbol = "ï˜ "

[git_commit]
only_detached = true

[git_metrics]
disabled = false

[golang]
symbol = "î˜§ "

[python]
disabled = false

# [java]
# symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "
threshold = 5
disabled = false

[nodejs]
symbol = "îœ˜ "

# [package]
# symbol = "ï£– "

[rust]
symbol = "î¨ "

[ruby]
symbol = "ğŸ’ "

# [shell]
# unknown_indicator = 'mystery shell'
# style = 'red bold'
# disabled = false
